version: "3.9"
name: moderate-diva-build

services:
   
   connector:
      image: "${DOCKER_REGISTRY}/${DOCKER_PROJECT}/s3-connector:${DOCKER_TAG}"
      container_name: moderate-connector
      build:
         context: ./diva/connector
         dockerfile: ./Dockerfile

   converter:
      container_name: moderate-converter
      image: "${DOCKER_REGISTRY}/${DOCKER_PROJECT}/converter:${DOCKER_TAG}"
      build:
         context: ./diva/converter
         dockerfile: ./Dockerfile

   reporter:
      container_name: moderate-reporter
      image: "${DOCKER_REGISTRY}/${DOCKER_PROJECT}/reporter:${DOCKER_TAG}"
      build:
         context: ./diva/reporter
         dockerfile: ./Dockerfile