# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation_task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15simulation_task.proto\x12\x10model.simulation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x06\n\x0eSimulationTask\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x05state\x18\x02 \x01(\x0e\x32&.model.simulation.SimulationTask.State\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x43\n\ninput_data\x18\x04 \x03(\x0b\x32/.model.simulation.SimulationTask.InputDataEntry\x12G\n\x0c\x62yte_results\x18\x07 \x03(\x0b\x32\x31.model.simulation.SimulationTask.ByteResultsEntry\x12I\n\rfloat_results\x18\x08 \x03(\x0b\x32\x32.model.simulation.SimulationTask.FloatResultsEntry\x12K\n\x0estring_results\x18\t \x03(\x0b\x32\x33.model.simulation.SimulationTask.StringResultsEntry\x1a\x30\n\x0eInputDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a\x32\n\x10\x42yteResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1aQ\n\x11\x46loatResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.model.simulation.FloatArray:\x02\x38\x01\x1aS\n\x12StringResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.model.simulation.StringArray:\x02\x38\x01\"n\n\x05State\x12%\n!SIMULATION_TASK_STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PLANNED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\n\n\x06PAUSED\x10\x03\x12\r\n\tCOMPLETED\x10\x04\x12\t\n\x05\x45RROR\x10\x05\"\x1d\n\nFloatArray\x12\x0f\n\x07\x65lement\x18\x01 \x03(\x02\"\x1e\n\x0bStringArray\x12\x0f\n\x07\x65lement\x18\x01 \x03(\tB<\n\"com.links.replica.model.simulationB\x14SimulationTaskProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.links.replica.model.simulationB\024SimulationTaskProtosP\001'
  _SIMULATIONTASK_INPUTDATAENTRY._options = None
  _SIMULATIONTASK_INPUTDATAENTRY._serialized_options = b'8\001'
  _SIMULATIONTASK_BYTERESULTSENTRY._options = None
  _SIMULATIONTASK_BYTERESULTSENTRY._serialized_options = b'8\001'
  _SIMULATIONTASK_FLOATRESULTSENTRY._options = None
  _SIMULATIONTASK_FLOATRESULTSENTRY._serialized_options = b'8\001'
  _SIMULATIONTASK_STRINGRESULTSENTRY._options = None
  _SIMULATIONTASK_STRINGRESULTSENTRY._serialized_options = b'8\001'
  _globals['_SIMULATIONTASK']._serialized_start=77
  _globals['_SIMULATIONTASK']._serialized_end=883
  _globals['_SIMULATIONTASK_INPUTDATAENTRY']._serialized_start=503
  _globals['_SIMULATIONTASK_INPUTDATAENTRY']._serialized_end=551
  _globals['_SIMULATIONTASK_BYTERESULTSENTRY']._serialized_start=553
  _globals['_SIMULATIONTASK_BYTERESULTSENTRY']._serialized_end=603
  _globals['_SIMULATIONTASK_FLOATRESULTSENTRY']._serialized_start=605
  _globals['_SIMULATIONTASK_FLOATRESULTSENTRY']._serialized_end=686
  _globals['_SIMULATIONTASK_STRINGRESULTSENTRY']._serialized_start=688
  _globals['_SIMULATIONTASK_STRINGRESULTSENTRY']._serialized_end=771
  _globals['_SIMULATIONTASK_STATE']._serialized_start=773
  _globals['_SIMULATIONTASK_STATE']._serialized_end=883
  _globals['_FLOATARRAY']._serialized_start=885
  _globals['_FLOATARRAY']._serialized_end=914
  _globals['_STRINGARRAY']._serialized_start=916
  _globals['_STRINGARRAY']._serialized_end=946
# @@protoc_insertion_point(module_scope)
