name: Mirror GitLab Repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIV_KEY }}

      - name: Mirror repository
        run: |
          git clone --mirror https://git.pertforge.ismb.it/moderate/diva.git
          cd diva.git
          git push --mirror git@github.com:MODERATE-Project/moderate-diva.git