name: Docker Compose Build

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Private Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load .env file
        run: |
          sudo apt-get install -y dotenv
          dotenv -f .env

      - name: Build and push
        run: |
          docker-compose -f docker-compose.build.yaml build
          docker-compose -f docker-compose.build.yaml push