# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x02\x64q\"\xd5\x04\n\x06Sample\x12\n\n\x02ts\x18\x01 \x01(\x04\x12 \n\x05state\x18\x02 \x01(\x0e\x32\x11.dq.Sample.States\x12\x0b\n\x03key\x18\x03 \x01(\t\x12-\n\nfloat_data\x18\x04 \x03(\x0b\x32\x19.dq.Sample.FloatDataEntry\x12/\n\x0bstring_data\x18\x05 \x03(\x0b\x32\x1a.dq.Sample.StringDataEntry\x12+\n\tbool_data\x18\x06 \x03(\x0b\x32\x18.dq.Sample.BoolDataEntry\x12\x0f\n\x07\x64\x61taset\x18\x07 \x01(\t\x12*\n\x08metadata\x18\x08 \x03(\x0b\x32\x18.dq.Sample.MetadataEntry\x1a@\n\x0e\x46loatDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.dq.FloatArray:\x02\x38\x01\x1a\x42\n\x0fStringDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.dq.StringArray:\x02\x38\x01\x1a>\n\rBoolDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.dq.BoolArray:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x06States\x12\x07\n\x03RAW\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\t\n\x05VALID\x10\x02\x12\x08\n\x04\x46\x41IL\x10\x03\x12\x0e\n\nAGGREGATED\x10\x04\x12\x0e\n\nANONYMIZED\x10\x05\"\x1d\n\nFloatArray\x12\x0f\n\x07\x65lement\x18\x01 \x03(\x02\"\x1e\n\x0bStringArray\x12\x0f\n\x07\x65lement\x18\x01 \x03(\t\"\x1c\n\tBoolArray\x12\x0f\n\x07\x65lement\x18\x01 \x03(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAMPLE_FLOATDATAENTRY']._options = None
  _globals['_SAMPLE_FLOATDATAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE_STRINGDATAENTRY']._options = None
  _globals['_SAMPLE_STRINGDATAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE_BOOLDATAENTRY']._options = None
  _globals['_SAMPLE_BOOLDATAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE_METADATAENTRY']._options = None
  _globals['_SAMPLE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLE']._serialized_start=21
  _globals['_SAMPLE']._serialized_end=618
  _globals['_SAMPLE_FLOATDATAENTRY']._serialized_start=292
  _globals['_SAMPLE_FLOATDATAENTRY']._serialized_end=356
  _globals['_SAMPLE_STRINGDATAENTRY']._serialized_start=358
  _globals['_SAMPLE_STRINGDATAENTRY']._serialized_end=424
  _globals['_SAMPLE_BOOLDATAENTRY']._serialized_start=426
  _globals['_SAMPLE_BOOLDATAENTRY']._serialized_end=488
  _globals['_SAMPLE_METADATAENTRY']._serialized_start=490
  _globals['_SAMPLE_METADATAENTRY']._serialized_end=537
  _globals['_SAMPLE_STATES']._serialized_start=539
  _globals['_SAMPLE_STATES']._serialized_end=618
  _globals['_FLOATARRAY']._serialized_start=620
  _globals['_FLOATARRAY']._serialized_end=649
  _globals['_STRINGARRAY']._serialized_start=651
  _globals['_STRINGARRAY']._serialized_end=681
  _globals['_BOOLARRAY']._serialized_start=683
  _globals['_BOOLARRAY']._serialized_end=711
# @@protoc_insertion_point(module_scope)
